// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: CreateRedirect/createRedirect.proto

package CreateRedirect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timer int32

const (
	Timer_start Timer = 0
	Timer_end   Timer = 1
)

// Enum value maps for Timer.
var (
	Timer_name = map[int32]string{
		0: "start",
		1: "end",
	}
	Timer_value = map[string]int32{
		"start": 0,
		"end":   1,
	}
)

func (x Timer) Enum() *Timer {
	p := new(Timer)
	*p = x
	return p
}

func (x Timer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Timer) Descriptor() protoreflect.EnumDescriptor {
	return file_CreateRedirect_createRedirect_proto_enumTypes[0].Descriptor()
}

func (Timer) Type() protoreflect.EnumType {
	return &file_CreateRedirect_createRedirect_proto_enumTypes[0]
}

func (x Timer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Timer.Descriptor instead.
func (Timer) EnumDescriptor() ([]byte, []int) {
	return file_CreateRedirect_createRedirect_proto_rawDescGZIP(), []int{0}
}

type CreateRedirectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source    string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destation string `protobuf:"bytes,2,opt,name=destation,proto3" json:"destation,omitempty"`
	Timer     Timer  `protobuf:"varint,3,opt,name=timer,proto3,enum=Timer" json:"timer,omitempty"`
}

func (x *CreateRedirectRequest) Reset() {
	*x = CreateRedirectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CreateRedirect_createRedirect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedirectRequest) ProtoMessage() {}

func (x *CreateRedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CreateRedirect_createRedirect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedirectRequest.ProtoReflect.Descriptor instead.
func (*CreateRedirectRequest) Descriptor() ([]byte, []int) {
	return file_CreateRedirect_createRedirect_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRedirectRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateRedirectRequest) GetDestation() string {
	if x != nil {
		return x.Destation
	}
	return ""
}

func (x *CreateRedirectRequest) GetTimer() Timer {
	if x != nil {
		return x.Timer
	}
	return Timer_start
}

type CreateRedirectRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Timer  Timer `protobuf:"varint,2,opt,name=timer,proto3,enum=Timer" json:"timer,omitempty"`
}

func (x *CreateRedirectRespond) Reset() {
	*x = CreateRedirectRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CreateRedirect_createRedirect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRedirectRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRedirectRespond) ProtoMessage() {}

func (x *CreateRedirectRespond) ProtoReflect() protoreflect.Message {
	mi := &file_CreateRedirect_createRedirect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRedirectRespond.ProtoReflect.Descriptor instead.
func (*CreateRedirectRespond) Descriptor() ([]byte, []int) {
	return file_CreateRedirect_createRedirect_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRedirectRespond) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *CreateRedirectRespond) GetTimer() Timer {
	if x != nil {
		return x.Timer
	}
	return Timer_start
}

var File_CreateRedirect_createRedirect_proto protoreflect.FileDescriptor

var file_CreateRedirect_createRedirect_proto_rawDesc = []byte{
	0x0a, 0x23, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x05, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x22, 0x4d, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x06, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65,
	0x72, 0x2a, 0x1b, 0x0a, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x10, 0x01, 0x32, 0x5b,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x70, 0x69, 0x63, 0x73, 0x65,
	0x76, 0x65, 0x6e, 0x2d, 0x63, 0x75, 0x70, 0x2f, 0x66, 0x6c, 0x75, 0x66, 0x66, 0x79, 0x2d, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x2f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CreateRedirect_createRedirect_proto_rawDescOnce sync.Once
	file_CreateRedirect_createRedirect_proto_rawDescData = file_CreateRedirect_createRedirect_proto_rawDesc
)

func file_CreateRedirect_createRedirect_proto_rawDescGZIP() []byte {
	file_CreateRedirect_createRedirect_proto_rawDescOnce.Do(func() {
		file_CreateRedirect_createRedirect_proto_rawDescData = protoimpl.X.CompressGZIP(file_CreateRedirect_createRedirect_proto_rawDescData)
	})
	return file_CreateRedirect_createRedirect_proto_rawDescData
}

var file_CreateRedirect_createRedirect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CreateRedirect_createRedirect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_CreateRedirect_createRedirect_proto_goTypes = []interface{}{
	(Timer)(0),                    // 0: Timer
	(*CreateRedirectRequest)(nil), // 1: CreateRedirectRequest
	(*CreateRedirectRespond)(nil), // 2: CreateRedirectRespond
}
var file_CreateRedirect_createRedirect_proto_depIdxs = []int32{
	0, // 0: CreateRedirectRequest.timer:type_name -> Timer
	0, // 1: CreateRedirectRespond.timer:type_name -> Timer
	1, // 2: CreateRedirectService.CreateRedirect:input_type -> CreateRedirectRequest
	2, // 3: CreateRedirectService.CreateRedirect:output_type -> CreateRedirectRespond
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CreateRedirect_createRedirect_proto_init() }
func file_CreateRedirect_createRedirect_proto_init() {
	if File_CreateRedirect_createRedirect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CreateRedirect_createRedirect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRedirectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_CreateRedirect_createRedirect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRedirectRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CreateRedirect_createRedirect_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CreateRedirect_createRedirect_proto_goTypes,
		DependencyIndexes: file_CreateRedirect_createRedirect_proto_depIdxs,
		EnumInfos:         file_CreateRedirect_createRedirect_proto_enumTypes,
		MessageInfos:      file_CreateRedirect_createRedirect_proto_msgTypes,
	}.Build()
	File_CreateRedirect_createRedirect_proto = out.File
	file_CreateRedirect_createRedirect_proto_rawDesc = nil
	file_CreateRedirect_createRedirect_proto_goTypes = nil
	file_CreateRedirect_createRedirect_proto_depIdxs = nil
}
