// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: api/createRedirect.proto

package CreateRedirect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CreateRedirectServiceClient is the client API for CreateRedirectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CreateRedirectServiceClient interface {
	CreateRedirect(ctx context.Context, in *CreateRedirectRequest, opts ...grpc.CallOption) (*CreateRedirectRespond, error)
}

type createRedirectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCreateRedirectServiceClient(cc grpc.ClientConnInterface) CreateRedirectServiceClient {
	return &createRedirectServiceClient{cc}
}

func (c *createRedirectServiceClient) CreateRedirect(ctx context.Context, in *CreateRedirectRequest, opts ...grpc.CallOption) (*CreateRedirectRespond, error) {
	out := new(CreateRedirectRespond)
	err := c.cc.Invoke(ctx, "/CreateRedirectService/CreateRedirect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateRedirectServiceServer is the server API for CreateRedirectService service.
// All implementations must embed UnimplementedCreateRedirectServiceServer
// for forward compatibility
type CreateRedirectServiceServer interface {
	CreateRedirect(context.Context, *CreateRedirectRequest) (*CreateRedirectRespond, error)
	mustEmbedUnimplementedCreateRedirectServiceServer()
}

// UnimplementedCreateRedirectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCreateRedirectServiceServer struct {
}

func (UnimplementedCreateRedirectServiceServer) CreateRedirect(context.Context, *CreateRedirectRequest) (*CreateRedirectRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRedirect not implemented")
}
func (UnimplementedCreateRedirectServiceServer) mustEmbedUnimplementedCreateRedirectServiceServer() {}

// UnsafeCreateRedirectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CreateRedirectServiceServer will
// result in compilation errors.
type UnsafeCreateRedirectServiceServer interface {
	mustEmbedUnimplementedCreateRedirectServiceServer()
}

func RegisterCreateRedirectServiceServer(s grpc.ServiceRegistrar, srv CreateRedirectServiceServer) {
	s.RegisterService(&CreateRedirectService_ServiceDesc, srv)
}

func _CreateRedirectService_CreateRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CreateRedirectServiceServer).CreateRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CreateRedirectService/CreateRedirect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CreateRedirectServiceServer).CreateRedirect(ctx, req.(*CreateRedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CreateRedirectService_ServiceDesc is the grpc.ServiceDesc for CreateRedirectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CreateRedirectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CreateRedirectService",
	HandlerType: (*CreateRedirectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRedirect",
			Handler:    _CreateRedirectService_CreateRedirect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/createRedirect.proto",
}
